//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Requests = new HashSet<Requests>();
            this.TheHistoryOfSuppliesOfMaterials = new HashSet<TheHistoryOfSuppliesOfMaterials>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronomic { get; set; }
        public int Position { get; set; }
        public System.DateTime Birthday { get; set; }
        public string IssuedByWhom { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string UnitCode { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public string CurrentAccountNumber { get; set; }
        public string CorrespondentAccountNumber { get; set; }
        public int BIK { get; set; }
        public string FullNameOfTheBank { get; set; }
        public bool HavingAFamily { get; set; }
        public string HealthStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheHistoryOfSuppliesOfMaterials> TheHistoryOfSuppliesOfMaterials { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
