//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FloorMasterEntities : DbContext
    {
        public FloorMasterEntities()
            : base("name=FloorMasterEntities")
        {
        }
        private static FloorMasterEntities _context;
        public static FloorMasterEntities GetContext()
        {
            if (_context == null)
            {
                _context = new FloorMasterEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<HistoryOfChangesInTheAmountOfMaterialInStock> HistoryOfChangesInTheAmountOfMaterialInStock { get; set; }
        public virtual DbSet<HistoryOfChangesInTheQuantityOfProductsInStock> HistoryOfChangesInTheQuantityOfProductsInStock { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PointOfSale> PointOfSale { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<TheFormOfTheOrganization> TheFormOfTheOrganization { get; set; }
        public virtual DbSet<TheHistoryOfChangesInTheMinimumCostForThePartner> TheHistoryOfChangesInTheMinimumCostForThePartner { get; set; }
        public virtual DbSet<TheHistoryOfSuppliesOfMaterials> TheHistoryOfSuppliesOfMaterials { get; set; }
        public virtual DbSet<TypeOfMaterials> TypeOfMaterials { get; set; }
        public virtual DbSet<TypeOfProducts> TypeOfProducts { get; set; }
        public virtual DbSet<UnitsOfMeasurement> UnitsOfMeasurement { get; set; }
    }
}
