//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.HistoryOfChangesInTheQuantityOfProductsInStock = new HashSet<HistoryOfChangesInTheQuantityOfProductsInStock>();
            this.Requests = new HashSet<Requests>();
            this.Materials = new HashSet<Materials>();
        }
    
        public string Article { get; set; }
        public int TypeOfProduct { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public int Height { get; set; }
        public Nullable<double> WeightWithoutPackaging { get; set; }
        public Nullable<double> WeightWithPackaging { get; set; }
        public byte[] QualityCertificate { get; set; }
        public string StandardNumber { get; set; }
        public Nullable<int> Время_изготовления { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> ShopNumber { get; set; }
        public Nullable<int> NumberOfPeopleInProduction { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfChangesInTheQuantityOfProductsInStock> HistoryOfChangesInTheQuantityOfProductsInStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual TypeOfProducts TypeOfProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
