//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public string TypeOfProduct { get; set; }
        public int Partner { get; set; }
        public int CountProduct { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Manger { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Partner Partner1 { get; set; }
        public virtual Products Products { get; set; }
    }
}
