//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorMaster.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheHistoryOfChangesInTheMinimumCostForThePartner
    {
        public int ID { get; set; }
        public string Article { get; set; }
        public Nullable<int> Partner { get; set; }
        public decimal MinimalCost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Partner Partner1 { get; set; }
    }
}
